name: Vérification automatique

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Afficher un message
        run: echo "Vérification réussie 🎉"
